name: Python test

on:
  push:
    branches:
      - main

jobs:
  test_python:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9, 3.11]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: python -m unittest

