name: Cron scheduled message

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  scheduled_message:
    runs-on: ubuntu-latest

    steps:
      - name: Print message
        run: echo "Scheduled build completed successfully!"
